### PR TITLE
Bugfix: Recognize `it.only.each` and other chains off of it.

### LINKED ISSUE #53: Parsing fails when using test.each`table`(name, fn, timeout)
From the Jest docs, you can structure a describe or a test like so
```typescript
test.each`
  a    | b    | expected
  ${1} | ${1} | ${2}
  ${1} | ${2} | ${3}
  ${2} | ${1} | ${3}
`('returns $expected when $a is added $b', ({a, b, expected}) => {
  expect(a + b).toBe(expected);
});
```
[reference](https://jestjs.io/docs/en/api#2--testeachtablename-fn-timeout-)

jest-editor-support does not recognize these expressions as tests in either v28.0.0 or v27.2.0.
I think this is similar, but different from the discussion had in https://github.com/jest-community/jest-editor-support/issues/29#issuecomment-578521119

### LINKED ISSUE #59: Does not parse `it` when used with more than one modifier
The Jest API includes a handful of modifiers to `it` that can be combined: `only`/`skip`, `concurrent`, and `each`.  Currently, the parser will detect an `it` if it has, at most, one modifier on it.  This means statements like `it.concurrent.each` are not detected.

Unsupported Jest API methods (from https://jestjs.io/docs/en/api):
* `describe.only.each(table)(name, fn)`
* `describe.skip.each(table)(name, fn)`
* ``describe.each`table`(name, fn)`` (and all variations above)
* `test.concurrent.each(table)(name, fn, timeout)`
* `test.concurrent.only.each(table)(name, fn)`
* `test.concurrent.skip.each(table)(name, fn)`
* `test.only.each(table)(name, fn)`
* `test.skip.each(table)(name, fn)`
* ``test.each`table`(name, fn)`` (and all variations above)

### PR DESCRIPTION
**Pull request by TheSench**
This PR enhances parsing of `it.each` and `describe.each` by allowing them to also be found when deeper in a property chain (e.g. `it.only.each`, `it.concurrent.only.each`, `describe.only.each`).  In addition, it also allows the **Tagged Template Literal** syntax of `it.each` and `describe.each` to be parsed.

It updates the logic that identifies `it` and `describe` blocks to walk up the callee chain to the root when there are multiple levels of callee (e.g. for `it.each(scenarios)(name, fn)`), and then to walk up the tag and object tree to the root (e.g. `each`->`only`->`concurrent`->`it`).

Jest API methods that should now be supported (from https://jestjs.io/docs/en/api):
* `describe.only.each(table)(name, fn)`
* `describe.skip.each(table)(name, fn)`
* ``describe.each`table`(name, fn)`` (and all variations above)
* `test.concurrent.each(table)(name, fn, timeout)`
* `test.concurrent.only.each(table)(name, fn)`
* `test.concurrent.skip.each(table)(name, fn)`
* `test.only.each(table)(name, fn)`
* `test.skip.each(table)(name, fn)`
* ``test.each`table`(name, fn)`` (and all variations above)

Fixes #53 
Fixes #59

### CODE REVIEW

File: src/parsers/babel_parser.js [hunk 1]
```diff
@@ -30,6 +30,20 @@ export const parse = (file: string, data: ?string, options: ?parser.ParserOption
...
+      rootForType = rootForType[type];
+    }
+    return rootForType;
+  };
+
+  const getRootCalleeOrSelf = node => getRootOfTypeOrSelf(node, 'callee');
+
+  const getRootTagOrSelf = node => getRootOfTypeOrSelf(node, 'tag');
+
+  const getRootObjectOrSelf = node => getRootOfTypeOrSelf(node, 'object');
```
Comment (connectdotz) [inline src/parsers/babel_parser.js]: I like your approach but it seems that we could make it more expressive...

```suggestion
  const deepGet = (node, ...types: string[]) => 
    types.reduce<BabelNode>((rootForType, type) => {
      while (rootForType[type]) {
        rootForType = rootForType[type];
      }
      return rootForType;
    }, node);
```

so we can call this with clear order below...

File: src/parsers/babel_parser.js [hunk 2]
```diff
@@ -76,11 +90,9 @@ export const parse = (file: string, data: ?string, options: ?parser.ParserOption
...
   // handle cases where it's a member expression (.only)
   const getNameForNode = node => {
-    if (isFunctionCall(node) && node && node.expression && node.expression.callee) {
-      const name =
-        node.expression.callee.name ||
-        node.expression.callee.object?.name ||
-        node.expression.callee.callee?.object?.name;
+    if (isFunctionCall(node) && node.expression.callee) {
+      const rootCallee = getRootCalleeOrSelf(node.expression);
+      const name = rootCallee.name || getRootObjectOrSelf(getRootTagOrSelf(rootCallee)).name;
```
Comment (connectdotz) [inline src/parsers/babel_parser.js]: use the `deepGet` above, we can express the order and attributes in a more readable way... (I know, I know, "readability" is rather subjective...)

```suggestion
      const callee = deepGet(node.expression, 'callee');
      const name =
        callee.name ||
        deepGet(callee, 'object').name ||
        deepGet(callee, 'tag').name ||
        deepGet(callee, 'tag', 'object').name;
```

**Review by connectdotz — COMMENTED** [review]
hey @TheSench thank you for submitting this PR, this is definitely a much-needed fix 👍 

I agree with the overall approach and your code does work. However, I think we can make the code more "expressive" for showing precedence and properties used. I made some suggestions below please take a look and see if it makes sense.

File: src/parsers/babel_parser.js (hunk 1 above)
Comment (TheSench) [reply src/parsers/babel_parser.js]: > I like your approach but it seems that we could make it more expressive...
> 
> so we can call this with clear order below...

I like this suggestion.

File: src/parsers/babel_parser.js (hunk 2 above)
Comment (TheSench) [reply src/parsers/babel_parser.js]: > use the `deepGet` above, we can express the order and attributes in a more readable way... (I know, I know, "readability" is rather subjective...)

I've added this, except I did not include `deepGet(callee, 'tag').name`, as that's not a valid case (`describe` or `it` themselves are never a tag).

Comment (connectdotz) [reply src/parsers/babel_parser.js]: good point

File: CHANGELOG.md [hunk 3]
```diff
@@ -4,6 +4,8 @@ Please add your own contribution below inside the Master section
 Bug-fixes within the same version aren't needed
 
 ## Master
+* Detect Tagged Template Literal version of describe.each and it.each
+* Detect it when used with deep chain of modifiers ( e.g. `test.concurrent.only.each(table)(name, fn)`)
```
Comment (connectdotz) [inline CHANGELOG.md]: as a convention, please attach the author's name at the end of the changelog.

File: fixtures/parser_tests.js [hunk 4]
```diff
@@ -385,6 +385,52 @@ function parserTests(parse: (file: string) => ParseResult, isTypescript = false)
       assertBlock2(itBlock, 2, 7, 4, 9, 'each test %p');
       assertNameInfo(itBlock, 'each test %p', 2, 33, 2, 44);
     });
+    
+    it('For the simplest it.each cases', () => {
```
Comment (connectdotz) [inline fixtures/parser_tests.js]: Seems like we are missing the corresponding `describe.each` test cases? Also might be worthy to add nested ".each" cases ...

File: fixtures/parser_tests.js [hunk 5]
```diff
@@ -401,6 +447,75 @@ function parserTests(parse: (file: string) => ParseResult, isTypescript = false)
       assertBlock2(itBlock, 2, 7, 6, 9, 'each test %p');
       assertNameInfo(itBlock, 'each test %p', 3, 10, 3, 21);
     });
+
+    it('For tagged template syntax', () => {
```
Comment (connectdotz) [inline fixtures/parser_tests.js:701]: good this one has both test and describe. Same comment as above, let's add some nested `.each` test cases to be thorough

File: src/parsers/babel_parser.js [hunk 6]
```diff
@@ -74,13 +83,16 @@ export const parse = (file: string, data: ?string, options: ?parser.ParserOption
...
+      const rootCallee = deepGet(node.expression, 'callee');
       const name =
-        node.expression.callee.name ||
-        node.expression.callee.object?.name ||
-        node.expression.callee.callee?.object?.name;
+        rootCallee.name ||
+        // handle cases where it's a member expression (e.g .only or .concurrent.only)
+        deepGet(rootCallee, 'object').name ||
+        // handle cases where it's part of a tag (e.g. .each`table`)
+        deepGet(rootCallee, 'tag', 'object').name;
```
Comment (connectdotz) [inline src/parsers/babel_parser.js:95]: great to add these comments! 👍

**Review by connectdotz — COMMENTED** [review]
Awesome, we are really close now. Just a few minor points about tests and changelog...

File: fixtures/parser_tests.js (hunk 4 above)
Comment (TheSench) [reply fixtures/parser_tests.js]: It added a similar describe.each suite.

File: fixtures/parser_tests.js (hunk 5 above)
Comment (TheSench) [reply fixtures/parser_tests.js:701]: I added a separate test fixture for some nested cases.

File: fixtures/parser_tests.js [hunk 7]
```diff
@@ -385,51 +412,274 @@ function parserTests(parse: (file: string) => ParseResult, isTypescript = false)
...
 
-      const fifthIt = data.itBlocks[4];
-      expect(fifthIt.name).toEqual('works with it.only');
-      expect(fifthIt.start).toEqual({column: 1, line: 18});
-      expect(fifthIt.end).toEqual({column: 3, line: 20});
+      assertParseResultSimple(parseResult, {
+        itBlocks: [
+          {
+            name: 'works with old functions',
+            start: { line: 2, column: 1 },
```
Comment (connectdotz) [inline fixtures/parser_tests.js:423]: looks like there is some prettier format inconsistency in this file... such as extra space in {}... 

Looks like ci didn't lint any file in fixtures thus missed it...

**Review by connectdotz — APPROVED** [review]
@TheSench thanks for the update, I did notice some prettier formate related issues. No big deal, I can fix it during merging.

Once again, thank you for the PR 👍
